"""add import_url column to Task

Revision ID: 3be435e5038c
Revises: 4290a873fda7
Create Date: 2016-01-20 15:58:45.362589

"""

# revision identifiers, used by Alembic.
revision = '3be435e5038c'
down_revision = '4290a873fda7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('import_url', sa.Unicode(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'import_url')
    ### end Alembic commands ###
